# Generated by Django 4.0 on 2022-02-28 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sex',
            options={'verbose_name_plural': 'Sex'},
        ),
    ]
