# Generated by Django 4.0 on 2022-02-28 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genders',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Genres',
            },
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('original_title', models.CharField(max_length=100)),
                ('overview', models.TextField(blank=True, null=True)),
                ('genre_ids', models.JSONField(blank=True, null=True)),
                ('release_date', models.CharField(blank=True, max_length=12, null=True)),
                ('vote_average', models.FloatField(blank=True, null=True)),
                ('poster_path', models.URLField(blank=True, max_length=255, null=True)),
                ('persons', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Movies',
            },
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Gender',
            },
        ),
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id_person', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('path_image', models.URLField(blank=True, max_length=255, null=True)),
                ('birthday', models.CharField(blank=True, max_length=12, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=255)),
                ('biography', models.TextField(blank=True, null=True)),
                ('known_for_department', models.CharField(blank=True, max_length=255)),
                ('sex', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Gender', to='api.sex')),
            ],
            options={
                'verbose_name_plural': 'Persons',
            },
        ),
    ]
