# Generated by Django 4.0 on 2022-01-22 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mywallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField(blank=True, null=True)),
                ('nameWallet', models.CharField(blank=True, max_length=64, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('date', models.CharField(blank=True, max_length=27, null=True)),
                ('username', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='User_Wallet', to='wallet.user')),
            ],
            options={
                'verbose_name_plural': 'Wallet',
            },
        ),
    ]
