# Generated by Django 4.0 on 2022-01-23 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_operations_op'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='operations',
            new_name='ops',
        ),
    ]
